---
output: html_document
---

## Examples 

```{r load-packges, message=FALSE, warning=FALSE}
library(aRtsy) # Ijeamaka Anyene's package for generative art 
library(flametree) # Danielle Navarro's package for generative art
library(MexBrewer) # Color Palettes Inspired by Works of Mexican Muralists
library(sf) # Simple Features for R
library(tidyverse) # Easily Install and Load the 'Tidyverse'
```

```{r}
load("df_mxstate_2020.RData")
```

```{r}
usethis::use_data(df_mxstate_2020, overwrite = TRUE)
```



<!--

```{r}
# Create waves using functions
wave_1 <- data.frame(x = seq(from = -2 * pi,
                             to = -0,
                             by = 0.01)) %>% 
  mutate(y = x * sin(5 * x + 0.2))

wave_2 <- data.frame(x = seq(from = -2 * pi,
                             to = -0,
                             by = 0.01)) %>% 
  mutate(y = x * sin(5 * x + 0.4) + 3)

wave_3 <- data.frame(x = seq(from = -2 * pi,
                             to = -0,
                             by = 0.01)) %>% 
  mutate(y = x * sin(5 * x + 0.8)  + 8)

wave_5 <- data.frame(x = seq(from = -2 * pi,
                             to = -0,
                             by = 0.01)) %>% 
  mutate(y = 0.5 * x * sin(5 * x + 1.5)  + 10)

ggplot() +
  geom_ribbon(data = wave_1,
              aes(x, 
                  ymin = 0.025 * x * (y - 0.025) - 0.1 * (x^2 - pi^2), 
                  ymax = 0.05 * x * (y + 0.025)),
              color = "black",
              fill = "orange") +
  geom_ribbon(data = wave_2,
              aes(x, 
                  ymin = 0.025 * x * (y - 0.025), 
                  ymax = 0.05 * x * (y + 0.025)),
              color = "black",
              fill = "blue") + 
geom_ribbon(data = wave_3,
              aes(x, 
                  ymin = 0.025 * x * (y - 0.025), 
                  ymax = 0.05 * x * (y + 0.025)),
              color = "black",
              fill = "yellow") +
    geom_ribbon(data = wave_4,
              aes(x, 
                  ymin = -0.025 * x * (y - 0.025) - 0.1 * (x^2 - pi^2), 
                  ymax = -0.05 * x * (y + 0.025)),
              color = "black",
              fill = "red") +
  geom_ribbon(data = wave_5,
              aes(x, 
                  ymin = 0.025 * x * (y - 0.025), 
                  ymax = 0.05 * x * (y + 0.025)),
              color = "black",
              fill = "green")


```

```{r}
# Create waves using functions
ggplot() +
  geom_rect(aes(xmin = -2 * pi, 
                xmax = 0, 
                ymin = -10 - 2.0,
                ymax = 10 + 2.0 ),
            size = 2.5,
            color = mex.brewer("Atentado")[9],
            fill = mex.brewer("Atentado")[4]) +
  # geom_ribbon(data = data.frame(x = seq(from = -2 * pi,
  #                            to = -0,
  #                            by = 0.01)) %>% 
  #               mutate(y = sin(5 * x + 0.2) - 11) %>%
  #               wave_maker(n = 10, shift = -2),
  #             aes(x, 
  #                 ymin = y - 2, 
  #                 ymax = y + 2,
  #                 group = group,
  #                 fill= factor(group)),
  #             color = NA) +
  geom_ribbon(data = data.frame(x = seq(from = -2 * pi,
                             to = -0,
                             by = 0.01)) %>% 
                mutate(y = x * sin(4 * x + 0.2) + 2) %>%
                wave_maker(n = 10, shift = 0.75),
              aes(x, 
                  ymin = y - 0.05 * (5 + x/2)^2, 
                  ymax = y + 0.05 * (5 - x/2)^2,
                  group = group,
                  fill= factor(group)),
              color = "white") +
  # geom_ribbon(data = data.frame(x = seq(from = -2 * pi,
  #                            to = -0,
  #                            by = 0.01)) %>% 
  #               mutate(y = x * sin(5 * x + 0.2) + 3) %>%
  #               wave_maker(n = 10, shift = 0.5),
  #             aes(x, 
  #                 ymin = 0.25 * x * (y - 0.025), 
  #                 ymax = 0.05 * x * (y + 0.025),
  #                 group = group,
  #                 fill= factor(group)),
  #             color = NA) +
  #ylim(c(-10, 10)) +
  geom_rect(aes(xmin = -2 * pi, 
                xmax = 0, 
                ymin = -10 - 2.0,
                ymax = 10 + 2.0 ),
            size = 2.5,
            color = "black",
            fill = NA) +
  scale_fill_manual(values = mex.brewer("Atentado", n = 10)) +
  theme_void() +
  theme(legend.position = "none")
```



```{r}
# Creating a function for iterations====

wave_maker_2 <- function(wave_df, n, y_shift, x_shift){
  
  #Create an empty list to store our multiple dataframes(waves)#
  wave_list<- list()
  
  #Create a for loop to iteratively make "n" waves shifted a distance `shift` from each other #
  for(i in seq_along(1:n)){
    
    wave_list[[i]] <- wave_df %>%
      mutate(y = y - (shift * i),
             group = i)  
  }
  
  #return the completed data frame to the environment#
  return(bind_rows(wave_list))
}
```


```{r}
wave_layers <- rbind(wave_1 %>%
                       wave_maker(n = 5, 
                                  shift = 0.5),
                     wave_2 %>%
                       wave_maker(n = 5, 
                                  shift = 1) %>%
                       mutate(group = group + 5))

col_palette <- mex.brewer("Alacena", n = 200)

ggplot(wave_layers) +
  geom_rect(aes(xmin = -2 * pi, 
                xmax = -pi, 
                ymin = min(y) - 2.0,
                ymax = max(y) + 2.0 ),
            size = 2.5,
            color = mex.brewer("Alacena")[9],
            fill = mex.brewer("Alacena")[4]) +
  geom_ribbon(aes(x, 
                  ymin = 0.025 * x * (y - 0.025), 
                  ymax = 0.1 * x * (y + 0.025), 
                  group = group, 
                  fill = group),
              color = "black",
              size = 0.5) + 
  geom_rect(aes(xmin = -2 * pi, 
                xmax = -pi, 
                ymin = min(y) - 2.0,
                ymax = max(y) + 2.0 ),
            size = 2.5,
            color = "black",
            fill = NA) +
  scale_fill_gradientn(colors = col_palette)+
  theme_void() +
  theme(legend.position = "none")

```

-->

